In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/yellow_tripdata_2016-03.csv')

print('=== Dados Carregados ===')
print(f'Total de linhas: {len(df):,}')
print(f'Total de colunas: {len(df.columns)}')
df.head()

=== Dados Carregados ===
Total de linhas: 12,210,952
Total de colunas: 19


,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,1,2016-03-01 00:00:00,2016-03-01 00:07:55,1,2.50,-73.976746,40.765152,1,N,-74.004265,40.746128,1,9.0,0.5,0.5,2.05,0.00,0.3,12.35
1,1,2016-03-01 00:00:00,2016-03-01 00:11:06,1,2.90,-73.983482,40.767925,1,N,-74.005943,40.733166,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35
2,2,2016-03-01 00:00:00,2016-03-01 00:31:06,2,19.98,-73.782021,40.644810,1,N,-73.974541,40.675770,1,54.5,0.5,0.5,8.00,0.00,0.3,63.80
3,2,2016-03-01 00:00:00,2016-03-01 00:00:00,3,10.78,-73.863419,40.769814,1,N,-73.969650,40.757767,1,31.5,0.0,0.5,3.78,5.54,0.3,41.62
4,2,2016-03-01 00:00:00,2016-03-01 00:00:00,5,30.43,-73.971741,40.792183,3,N,-74.177170,40.695053,1,98.0,0.0,0.0,0.00,15.50,0.3,113.80


In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12210952 entries, 0 to 12210951
Data columns (total 19 columns):
 #   Column                 Dtype  
---  ------                 -----  
 0   VendorID               int64  
 1   tpep_pickup_datetime   object 
 2   tpep_dropoff_datetime  object 
 3   passenger_count        int64  
 4   trip_distance          float64
 5   pickup_longitude       float64
 6   pickup_latitude        float64
 7   RatecodeID             int64  
 8   store_and_fwd_flag     object 
 9   dropoff_longitude      float64
 10  dropoff_latitude       float64
 11  payment_type           int64  
 12  fare_amount            float64
 13  extra                  float64
 14  mta_tax                float64
 15  tip_amount             float64
 16  tolls_amount           float64
 17  improvement_surcharge  float64
 18  total_amount           float64
dtypes: float64(12), int64(4), object(3)
memory usage: 1.7+ GB


In [4]:
pd.set_option('display.float_format', '{:.2f}'.format)

print(df.describe())

         VendorID  passenger_count  trip_distance  pickup_longitude  \
count 12210952.00      12210952.00    12210952.00       12210952.00   
mean         1.53             1.66           6.13            -72.87   
std          0.50             1.31        6156.48              8.96   
min          1.00             0.00           0.00           -161.70   
25%          1.00             1.00           1.00            -73.99   
50%          2.00             1.00           1.70            -73.98   
75%          2.00             2.00           3.18            -73.97   
max          2.00             9.00    19072628.80              0.00   

       pickup_latitude  RatecodeID  dropoff_longitude  dropoff_latitude  \
count      12210952.00 12210952.00        12210952.00       12210952.00   
mean             40.14        1.04             -72.94             40.18   
std               4.94        0.58               8.70              4.79   
min               0.00        1.00            -161.70       

In [5]:
for coluna in df.columns:
    print(f"\n--- {coluna} ---")
    print(df[coluna].unique())


--- VendorID ---
[1 2]

--- tpep_pickup_datetime ---
['2016-03-01 00:00:00' '2016-03-01 00:00:01' '2016-03-01 00:00:02' ...
 '2016-03-31 23:59:58' '2016-03-31 23:59:59' '2016-03-20 08:45:16']

--- tpep_dropoff_datetime ---
['2016-03-01 00:07:55' '2016-03-01 00:11:06' '2016-03-01 00:31:06' ...
 '2016-06-27 15:05:01' '2016-06-28 19:11:27' '2016-06-29 15:58:16']

--- passenger_count ---
[1 2 3 5 6 4 0 7 8 9]

--- trip_distance ---
[ 2.5   2.9  19.98 ... 59.7  50.67 47.67]

--- pickup_longitude ---
[-73.97674561 -73.98348236 -73.78202057 ... -74.0467453  -73.65337372
 -74.04075623]

--- pickup_latitude ---
[40.76515198 40.76792526 40.64480972 ... 40.65264511 40.86123276
 40.65416718]

--- RatecodeID ---
[ 1  3  2  5  4  6 99]

--- store_and_fwd_flag ---
['N' 'Y']

--- dropoff_longitude ---
[-74.00426483 -74.0059433  -73.97454071 ... -74.14380646 -74.17544556
 -74.19876099]

--- dropoff_latitude ---
[40.74612808 40.73316574 40.67576981 ... 40.58387756 40.54294205
 40.92243958]

--- payment

In [6]:
df['pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])
df['dropoff_datetime'] = pd.to_datetime(df['tpep_dropoff_datetime'])

print('=== Valores Nulos ===')
print(df.isnull().sum())

=== Valores Nulos ===
VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
pickup_longitude         0
pickup_latitude          0
RatecodeID               0
store_and_fwd_flag       0
dropoff_longitude        0
dropoff_latitude         0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
pickup_datetime          0
dropoff_datetime         0
dtype: int64


In [ ]:
total = len(df)

invalid_passenger_count = ((df['passenger_count'] <= 0) | (df['passenger_count'] > 4))

invalid_trip_distance = ((df['trip_distance'] <= 0) | (df['trip_distance'] > 100))

invalid_ratecodid = (df['RatecodeID'] > 6)

invalid_fare_amount = (df['fare_amount'] < 0)

invalid_duration = (df['pickup_datetime'] > df['dropoff_datetime'])

invalid_pickup_coords = (
    (df['pickup_latitude'] < 40.4) | (df['pickup_latitude'] > 41.0) |
    (df['pickup_longitude'] < -74.3) | (df['pickup_longitude'] > -73.7)
)
invalid_dropoff_coords = (
    (df['dropoff_latitude'] < 40.4) | (df['dropoff_latitude'] > 41.0) |
    (df['dropoff_longitude'] < -74.3) | (df['dropoff_longitude'] > -73.7)
)

print('=== Anomalias Encontradas ===')

print(f'Passageiros inválidos (<=0 ou >4):  {invalid_passenger_count.sum():,} ({invalid_passenger_count.sum()/total*100:.2f}%)')
print(f'Distância inválida (<=0 ou >100): {invalid_trip_distance.sum():,} ({invalid_trip_distance.sum()/total*100:.2f}%)')
print(f'RatecodeID inválido (>6):           {invalid_ratecodid.sum():,} ({invalid_ratecodid.sum()/total*100:.3f}%)')
print(f'Tarifa negativa:                    {invalid_fare_amount.sum():,} ({invalid_fare_amount.sum()/total*100:.2f}%)')
print(f'Duração inválida:                   {invalid_duration.sum():,} ({invalid_duration.sum()/total*100:.3f}%)')
print(f'Coordenadas pickup fora de NYC:     {invalid_pickup_coords.sum():,} ({invalid_pickup_coords.sum()/total*100:.2f}%)')
print(f'Coordenadas dropoff fora de NYC:    {invalid_dropoff_coords.sum():,} ({invalid_dropoff_coords.sum()/total*100:.2f}%)')


=== Anomalias Encontradas ===
Passageiros inválidos (<=0 ou >4):  1,050,645 (8.60%)
Distância inválida (<=0 ou >100): 71,225 (0.58%)
RatecodeID inválido (>6):           329 (0.003%)
Tarifa negativa:                    4,581 (0.04%)
Duração inválida:                   109 (0.001%)
Coordenadas pickup fora de NYC:     183,816 (1.51%)
Coordenadas dropoff fora de NYC:    178,754 (1.46%)


In [25]:
invalid_mask = (
    invalid_passenger_count |
    invalid_trip_distance |
    invalid_ratecodid |
    invalid_fare_amount |
    invalid_duration |
    invalid_pickup_coords |
    invalid_dropoff_coords
)

df_cleaned = df[~invalid_mask]

removed_rows = total - len(df_cleaned)
print(f'Total de linhas antes da remoção: {total:,}')
print(f'\nTotal de linhas removidas: {removed_rows:,} ({removed_rows/total*100:.2f}%)')
print(f'Total de linhas após a remoção: {len(df_cleaned):,}')


MemoryError: Unable to allocate 999. MiB for an array with shape (12, 10916775) and data type float64